#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
	passenger_status
	passenger_memory
	ps_httpd
	ps_delayed_job
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup ruby env"

echo "gem: --no-rdoc --no-ri " >> /opt/local/etc/gemrc
gem update --system
gem install bundler
gem install gemenv
gem install pkg-config

echo "* Setup ruby home"
groupadd -g 1100 ruby
useradd -m -s /usr/bin/bash -d /home/ruby -u 1100 -g ruby ruby
passwd -N ruby
passwd -d ruby

cat >> /home/ruby/.bashrc << EOF
source /home/ruby/www/shared/gems/bin/activate
EOF

mkdir -p /home/ruby/www/releases
mkdir -p /home/ruby/www/shared/config
mkdir -p /home/ruby/www/shared/content
mkdir -p /home/ruby/www/shared/log
mkdir -p /home/ruby/www/shared/system
cd /home/ruby/www/shared
/opt/local/bin/gemenv gems

mv /var/zoneinit/tmp/activate /home/ruby/www/shared/gems/bin/activate
mv /var/zoneinit/tmp/ruby /home/ruby/www/shared/gems/bin/ruby
chmod +x /home/ruby/www/shared/gems/bin/ruby
rm -rf /var/zoneinit/tmp
chown -R ruby:ruby /home/ruby/www

echo "* setup spiped"
groupadd -g 120 spiped
useradd -m -s /usr/bin/false -d /nonexistent -u 120 -g spiped spiped
dd if=/dev/urandom bs=32 count=1 2>/dev/null | shasum -a 512 | awk '{print $1}' | tr -d '\n' > /etc/ssh/spiped.key
chmod 0640 /etc/ssh/spiped.key
chown root:spiped /etc/ssh/spiped.key
svccfg delete svc:/pkgsrc/spiped:default

# Configuring image specific packages
echo "* Configuring image specific packages.";

mkdir -p /var/log/httpd/old

mkdir /opt/local/etc/httpd/tls
chmod 0600 /opt/local/etc/httpd/tls

chmod 0640 /opt/qutic/mysql-proxy/etc/my.cnf
svccfg import /opt/qutic/mysql-proxy/share/mysql-proxy.xml

echo "export PASSENGER_INSTANCE_REGISTRY_DIR=/var/tmp" >> /root/.bashrc

# ruby process watch
svccfg import /opt/qutic/lib/svc/manifest/rbpswatch.xml
# svcadm enable rbpswatch

# fix wrong passenger pkgsrc build 2017Q4 for ruby 2.4
ln -nfs /opt/local/lib/ruby/vendor_ruby/2.5.0 /opt/local/lib/ruby/vendor_ruby/2.2.0

# Clean up
echo "* Cleaning up."
#pkgin -y remove gmake
#pkgin -y remove gcc49
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
